### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wangsai-silence** [ton-blockchain/multisig-contract-v2#52]
machine:  Mac M1 Pro
node version: v20.15.0

commands: 

> yarn 
> yarn build --all

error info: 

```
[ 1][t 0][2024-06-24 02:41:34.015000][Fift.cpp:67]      top: <continuation 0xa67bb0>
level 1: <continuation 0xa67c30>
level 2: <text interpreter continuation>

Error: main.fif:273:    GETGASFEESIMPLE:-?
    at doCompileFunc (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/compile/compile.js:48:15)
    at async doCompileInner (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/compile/compile.js:103:12)
    at async doCompile (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/compile/compile.js:114:17)
    at async buildOne (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/build.js:21:24)
    at async buildAll (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/build.js:54:9)
    at async build (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/cli/build.js:23:9)
    at async main (/Users/will/code/multisig-contract-v2/node_modules/@ton/blueprint/dist/cli/cli.js:94:5)

```

**Comment by uddhavm** [comment]
did you figure this out @wangsai-silence ?
